FROM golang:1.24.3-alpine3.21

WORKDIR /src/test

COPY ./go.mod ./go.sum ..

COPY ./engine ../engine
COPY ./http ../http
COPY ./model ../model
COPY ./worker ../worker

COPY test/go.mod test/go.sum .

RUN go mod download

COPY test/bpmn ./bpmn
COPY test/*.go .

RUN CGO_ENABLED=0 GOOS=linux go build -o worker .

ENTRYPOINT ["worker"]
