name: Publish
on:
  push:
    branches:
      - "gh-page"
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Clean install
        run: npm ci
      - name: Build
        run: bash ./.github/workflows/build.sh v0.2.0 # need to be manually increased
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/
  deploy:
    runs-on: ubuntu-22.04
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy pages
        uses: actions/deploy-pages@v4
        id: deployment
