name: Test
on:
  push:
    branches:
      - "**"
      - "!master"
env:
  GO_VERSION: 1.24.3
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"
      - name: Run tests
        run: go test ./...
